config/routes.rb
Rails.application.routes.draw do
  get 'melbourne/home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :houses
  root 'melbourne#home'


  resources :houses do
    resources :locations
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
    has_many :locations
    validates :house_type, presence: true
end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :house
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
    def new
        @house = House.new
    end

    def edit
        @house = House.find(params[:id])
    end

    def create
        @house = House.new(house_params)
        if @house.save
          flash[:success] = "Object successfully created"
          redirect_to @house
        else
          flash[:error] = "Something went wrong"
          render 'new'
        end
    end
    
    def update
        @house = House.find(params[:id])
        if @house.update(house_params)
          flash[:success] = "Object was successfully updated"
          redirect_to @house
        else
          flash[:error] = "Something went wrong"
          render 'edit'
        end
    end

    def show
        @house = House.find(params[:id])
    end
    
    def destroy
        @house = House.find(params[:id])
        if @house.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to houses_path
        else
            flash[:error] = 'Something went wrong'
            redirect_to houses_path
        end
    end

    def index
        @houses = House.all
    end
    
    
    
    private
        def house_params
            params.require(:house).permit(:rooms, :house_type, :price, :method, :date)
        end
    
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
    def create
       @house = House.find(params[:house_id])
       @location = @house.locations.create(location_params)
       redirect_to @house
    end

    def destroy
        @house = House.find(params[:house_id])
        @location = @house.locations.find(params[:id])
        if @location.destroy
            flash[:success] = 'Object was successfully deleted.'
            redirect_to house_path(@house)
        else
            flash[:error] = 'Something went wrong'
            redirect_to house_path(@house)
        end
    end
    
    
    
    private
        def location_params
            params.require(:location).permit(:suburb, :address, :postcode, 
            :regionname, :propertycount, :distance)
        end
    
end

app/controllers/melbourne_controller.rb
class MelbourneController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/melbourne_helper.rb
module MelbourneHelper
end

app/views/houses/_form.html.erb
<div class='container'>
    <%= form_with model: @house, local: true do |form| %>

    <% if @house.errors.any? %>

        <div id='error_explanation' >
            <h2>
                <%= pluralize(@house.errors.count, 'error') %>
                    prohibited this article being saved:
            
            </h2>
                <% @house.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
        
        
        </div>
    
    <% end %>
    <p>
        <%= form.label :rooms %>
        <%= form.number_field( :rooms, min: 0) %>
    </p>

    <p>
        <%= form.label :house_type %>
        <%= form.select(:house_type, options_for_select([[
         'house,cottage,villa, semi,terrace', 'h'], ['townhouse','t'], ['unit, duplex','u'],
          ['bedroom(s)','br']]) ) %>
    </p>

    <p>
        <%= form.label :price %>
        <%= form.number_field( :price, min: 0, step: 0.01)  %>
    </p>

    <p>
        <%= form.label :method %>
        <%= form.select(:method,  options_for_select([['property sold','S'],
         ['property sold prior','SP'], ['property passed in','PI'], 
         ['sold not disclosed','SN'], ['no bid','VB'],
          ['sold after auction','SA'], ['sold prior not disclosed','PN']])) %>
    </p>

    <p>
        <%= form.label :date %>
        <%= form.date_field :date %>
    </p>

    <p>
        <%= form.submit %>
    </p>

<% end %>


</div>

app/views/houses/edit.html.erb
<h1>Edit House</h1>

<%= render 'form' %>


<%= link_to 'Back', houses_path %>

app/views/houses/index.html.erb
<h1>Listing Houses</h1>
<%= link_to 'New House', new_house_path %>
<div>
<table class='table table-bordered table-stripped'>
    <tr>
        <th>Rooms</th>
        <th>House Type</th>
        <th>Price</th>
        <th>Method</th>
        <th>Date Sold</th>
        <th clospan='3'></th>
    </tr>

    <% @houses.each do |house| %>

        <tr>
            <td><%= house.rooms  %></td>
             <td><%= house.house_type %> </td>
              <td><%= house.price %></td>
               <td><%= house.method %> </td>
                <td><%= house.date %> </td>
                 <td><%= link_to 'Show', house_path(house) %> </td>
                  <td><%= link_to 'Edit', edit_house_path(house) %> </td>
                   <td><%= link_to 'Destroy', house_path(house), method: :delete, 
                   data: {confirm: 'Are you sure?' }  %> </td>
        
        </tr>

    <% end %>

</table>

<%= link_to 'Home', melbourne_home_path  %>

app/views/houses/new.html.erb
<h1>New House</h1>

<%= render 'form' %>


<%= link_to 'Back', houses_path %>

app/views/houses/show.html.erb
<p>
    <strong>Rooms</strong>
    <%= @house.rooms %>
</p>

<p>
     <strong>House Type</strong>
    <%= @house.house_type %>
</p>

<p>
    <strong>Price</strong>
    <%= @house.price %>
</p>

<p>
    <strong>Method</strong>
    <%= @house.method %>
</p>

<p>
    <strong>Date sold</strong>
    <%= @house.date %>
</p>

<h2>Locations</h2>
<%= render @house.locations %>

<h2>Add a location:</h2>
<%= render 'locations/form' %>


<%= link_to 'Edit', edit_house_path(@house) %> |
<%= link_to 'Back', houses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MelbourneHousePrice</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.erb
<%= form_with(model: [ @house, @house.locations.build ],
    local: true) do |form|  %>
    <p>
        <%= form.label :suburb %>
        <%= form.text_field :suburb %>
    </p>
     <p>
        <%= form.label :address %>
        <%= form.text_field :address %>
    </p>
     <p>
        <%= form.label :postcode %>
        <%= form.text_field :postcode %>
    </p>
     <p>
        <%= form.label :regionname %>
        <%= form.text_field :regionname %>
    </p>
     <p>
        <%= form.label :propertycount %>
        <%= form.number_field :propertycount %>
    </p>
     <p>
        <%= form.label :distance %>
        <%= form.number_field( :distance, min: 0, step: 0.01)%>
    </p>

     <p>
        <%= form.submit %>
        
    </p>

<% end %>

app/views/locations/_location.html.erb
<p>
    <strong>Suburb:</strong>
    <%= location.suburb %>
</p>

<p>
    <strong>Address:</strong>
    <%= location.address %>
</p>

<p>
    <strong>Postcode:</strong>
    <%= location.postcode %>
</p>

<p>
    <strong>Region name:</strong>
    <%= location.regionname %>
</p>

<p>
    <strong>Propertycount:</strong>
    <%= location.propertycount %>
</p>

<p>
    <strong>Distance:</strong>
    <%= location.distance %>
</p>

<p>
<%= link_to 'Edit', edit_house_location_path(@house) %></p>
<p>
    <%= link_to 'Destroy Location', [location.house, location],
    method: :delete, data: { confirm: 'Are you sure?' } %>
</p>
<p><%= link_to 'Back', houses_path %></p>

app/views/melbourne/home.html.erb
<h1>Hello, Melbourne!</h1>

<%= link_to 'Houses', houses_path  %>